// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/eng/v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 域名查询请求
//
// 域名查询请求
type AppDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain string `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *AppDomainRequest) Reset() {
	*x = AppDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDomainRequest) ProtoMessage() {}

func (x *AppDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDomainRequest.ProtoReflect.Descriptor instead.
func (*AppDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AppDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AppDomainRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AppDomainRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AppDomainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=Urls,proto3" json:"Urls,omitempty"`
}

func (x *AppDomainResponse) Reset() {
	*x = AppDomainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDomainResponse) ProtoMessage() {}

func (x *AppDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDomainResponse.ProtoReflect.Descriptor instead.
func (*AppDomainResponse) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AppDomainResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AppPortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
}

func (x *AppPortRequest) Reset() {
	*x = AppPortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPortRequest) ProtoMessage() {}

func (x *AppPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPortRequest.ProtoReflect.Descriptor instead.
func (*AppPortRequest) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *AppPortRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type AppPortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 开放的端口
	//
	// 开放的端口
	Port []int64 `protobuf:"varint,1,rep,packed,name=Port,proto3" json:"Port,omitempty"`
}

func (x *AppPortResponse) Reset() {
	*x = AppPortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPortResponse) ProtoMessage() {}

func (x *AppPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPortResponse.ProtoReflect.Descriptor instead.
func (*AppPortResponse) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *AppPortResponse) GetPort() []int64 {
	if x != nil {
		return x.Port
	}
	return nil
}

type AppUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *AppUrlRequest) Reset() {
	*x = AppUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUrlRequest) ProtoMessage() {}

func (x *AppUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUrlRequest.ProtoReflect.Descriptor instead.
func (*AppUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *AppUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AppUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=Urls,proto3" json:"Urls,omitempty"`
}

func (x *AppUrlResponse) Reset() {
	*x = AppUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eng_v1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUrlResponse) ProtoMessage() {}

func (x *AppUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_eng_v1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUrlResponse.ProtoReflect.Descriptor instead.
func (*AppUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_eng_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *AppUrlResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_api_eng_v1_api_proto protoreflect.FileDescriptor

var file_api_eng_v1_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x22, 0x58, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x27, 0x0a, 0x11,
	0x41, 0x70, 0x70, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a,
	0x0e, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x22,
	0x25, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x21, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x0e, 0x41, 0x70, 0x70,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x55, 0x72, 0x6c, 0x73, 0x32,
	0xe6, 0x01, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x4e, 0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x41, 0x70, 0x70, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x65, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x45, 0x0a, 0x0c, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x55, 0x72,
	0x6c, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x70, 0x70, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x65, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x4d, 0x6f, 0x6f, 0x6e,
	0x5f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x67, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_eng_v1_api_proto_rawDescOnce sync.Once
	file_api_eng_v1_api_proto_rawDescData = file_api_eng_v1_api_proto_rawDesc
)

func file_api_eng_v1_api_proto_rawDescGZIP() []byte {
	file_api_eng_v1_api_proto_rawDescOnce.Do(func() {
		file_api_eng_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_eng_v1_api_proto_rawDescData)
	})
	return file_api_eng_v1_api_proto_rawDescData
}

var file_api_eng_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_eng_v1_api_proto_goTypes = []interface{}{
	(*AppDomainRequest)(nil),  // 0: api.eng.v1.AppDomainRequest
	(*AppDomainResponse)(nil), // 1: api.eng.v1.AppDomainResponse
	(*Status)(nil),            // 2: api.eng.v1.Status
	(*AppPortRequest)(nil),    // 3: api.eng.v1.AppPortRequest
	(*AppPortResponse)(nil),   // 4: api.eng.v1.AppPortResponse
	(*AppUrlRequest)(nil),     // 5: api.eng.v1.AppUrlRequest
	(*AppUrlResponse)(nil),    // 6: api.eng.v1.AppUrlResponse
}
var file_api_eng_v1_api_proto_depIdxs = []int32{
	0, // 0: api.eng.v1.App.handleAppDomain:input_type -> api.eng.v1.AppDomainRequest
	3, // 1: api.eng.v1.App.handleAppPort:input_type -> api.eng.v1.AppPortRequest
	5, // 2: api.eng.v1.App.handleAppUrl:input_type -> api.eng.v1.AppUrlRequest
	1, // 3: api.eng.v1.App.handleAppDomain:output_type -> api.eng.v1.AppDomainResponse
	4, // 4: api.eng.v1.App.handleAppPort:output_type -> api.eng.v1.AppPortResponse
	6, // 5: api.eng.v1.App.handleAppUrl:output_type -> api.eng.v1.AppUrlResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_eng_v1_api_proto_init() }
func file_api_eng_v1_api_proto_init() {
	if File_api_eng_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_eng_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eng_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDomainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eng_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eng_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppPortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eng_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppPortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eng_v1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eng_v1_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_eng_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_eng_v1_api_proto_goTypes,
		DependencyIndexes: file_api_eng_v1_api_proto_depIdxs,
		MessageInfos:      file_api_eng_v1_api_proto_msgTypes,
	}.Build()
	File_api_eng_v1_api_proto = out.File
	file_api_eng_v1_api_proto_rawDesc = nil
	file_api_eng_v1_api_proto_goTypes = nil
	file_api_eng_v1_api_proto_depIdxs = nil
}
